version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
  pre_build: 
    commands:
     - npm install
     - npm test
  build:
    commands:
     - npm run webpack
artifacts:
  files:
    - index.html
    - codesample.html
    - error.html
    - favicon.ico
    - John_Cook.pdf
    - styles/*
    - images/*
    - dist/bundle.js