version: 0.1

phases:
   build:
     commands:
       - npm install
       - npm run webpack
artifacts:
  files:
    - index.html
    - error.html
    - favicon.ico
    - John_Cook.pdf
    - styles/*
    - images/*
    - dist/bundle.js